name: 'Plerion Shift Left Action'
description:
  'Stop misconfigurations before they make it to production. Shift left with
  Infrastructure as Code (IaC) Scanning'
author: 'Noel Llevares'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
